[package]
name = "kvs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.3.0"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
failure = "0.1.5"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
